name: Kryptonite
version: '${project.version}'
main: net.lewmc.kryptonite.Kryptonite
author: LewMC
description: The Kryptonite of lag.
website: https://lewmc.net
api-version: '1.20'
load: POSTWORLD
commands:
  kryptonite:
    description: Main command
    usage: /<command>
    aliases: ['krypt','kr']
  kos:
    description: Kryptonite Optimisation System
    usage: /<command>
    aliases: ['optimise','optimize']
  edb:
    description: Exploit Database
    usage: /<command>
    aliases: ['exploit']