---
name: Bug report
description: Create a report to help us improve our software.
title: Bug report
labels: bug
assignees: "LewMilburn"
body:
- type: textarea
  attributes:
    label: "Please describe the bug"
    description: "Please provide a clear and concise description of what the bug is."
- type: textarea
  attributes:
    label: "Steps to reproduce the behavior"
    description: "What steps can we take to make the same bug or issue happen in our testing environment? What did you do before the issue happened?"
- type: textarea
  attributes:
    label: "Expected behavior"
    description: "What did you expect to happen instead of the issue you're reporting?"
- type: textarea
  attributes:
    label: "Server information:"
    value: "Minecraft Version: [e.g. 1.20.4] - Server Implementation: [e.g. Bukkit, Spigot, Paper, etc.] - Kryptonite Version: [e.g. 1.1.0]"
- type: textarea
  attributes:
    label: "Please enter a link to your logs"
    description: "Links to logs are extremely helpful. We recommend using https://mclo.gs/"
- type: textarea
  attributes:
    label: "Anything else?"
    description: "Please enter any additional information here:"
---
